from analysis.src.analyzers import (
    AbstractMetricAnalyzer,
    BooleanMetricAnalyzer,
    ConditionalLERAnalyzer,
    NumericMetricAnalyzer,
    PostselectionResult,
)
from analysis.src.config import ConditionalLERConfig, PlotConfig
from analysis.src.data_manager import SimulationDataManager
from analysis.src.postselect import (
    PostSelectCurve,
    PostSelectSpec,
    PostSelectionPlotter,
    postselect_curve_ar,
    postselect_curve_continuous,
)
from analysis.src.relative_improvement import (
    RelImprovSpec,
    RelativeImprovementPlotter,
)
from analysis.src.metric_correlation import (
    MetricPairConfig,
    concordance_correlation_coefficient,
    plot_metric_scatter,
)
from analysis.src.metric_spearman import (
    SpearmanConfig,
    compute_spearman_matrix,
    plot_spearman_heatmap,
)
from analysis.src.case_histogram import (
    ForcedGapMLCaseConfig,
    ForcedGapMLCaseAnalyzer,
    GapCaseHistogramConfig,
    CaseScatterConfig,
    CASE_TICK_LABELS,
    CASE_DESCRIPTIONS,
    case_description_text,
    LogicalGapSplitConfig,
    LogicalGapSplitAnalyzer,
    OverrideProbabilityConfig,
    OverrideProbabilityAnalyzer,
)
from analysis.src.figure_style import (
    MultiStyleFigureExporter,
    apply_paper_style,
    set_tab10_colors,
    finalize_axes,
    TAB10_COLORS,
)
from analysis.src.plot_utils import (
    PlotOutputOptions,
    finalize_plot,
    draw_numeric_distribution,
    draw_boolean_distribution,
    draw_conditional_ler,
    draw_conditional_ler_fitting,
    draw_post_selection,
    draw_relative_improvement,
    draw_case_histogram,
    draw_case_scatter,
    draw_logical_gap_split_by_case,
    draw_override_probability,
    draw_override_gap_histogram,
)

__all__ = [
    "PlotConfig",
    "ConditionalLERConfig",
    "SimulationDataManager",
    "AbstractMetricAnalyzer",
    "NumericMetricAnalyzer",
    "BooleanMetricAnalyzer",
    "ConditionalLERAnalyzer",
    "PostselectionResult",
    "PostSelectSpec",
    "PostSelectCurve",
    "PostSelectionPlotter",
    "postselect_curve_continuous",
    "postselect_curve_ar",
    "RelImprovSpec",
    "RelativeImprovementPlotter",
    "MetricPairConfig",
    "concordance_correlation_coefficient",
    "plot_metric_scatter",
    "SpearmanConfig",
    "compute_spearman_matrix",
    "plot_spearman_heatmap",
    "ForcedGapMLCaseConfig",
    "ForcedGapMLCaseAnalyzer",
    "CaseScatterConfig",
    "CASE_TICK_LABELS",
    "CASE_DESCRIPTIONS",
    "case_description_text",
    "LogicalGapSplitConfig",
    "LogicalGapSplitAnalyzer",
    "OverrideProbabilityConfig",
    "OverrideProbabilityAnalyzer",
    "MultiStyleFigureExporter",
    "apply_paper_style",
    "set_tab10_colors",
    "finalize_axes",
    "TAB10_COLORS",
    "PlotOutputOptions",
    "finalize_plot",
    "draw_numeric_distribution",
    "draw_boolean_distribution",
    "draw_conditional_ler",
    "draw_conditional_ler_fitting",
    "draw_post_selection",
    "draw_relative_improvement",
    "draw_case_histogram",
    "draw_case_scatter",
    "draw_logical_gap_split_by_case",
    "draw_override_probability",
    "draw_override_gap_histogram",
]
